const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_LOGIN_SUCCESS1: 'ADMIN_LOGIN_SUCCESS1',
    ADMIN_LOGIN_FAIL1: 'ADMIN_LOGIN_FAIL1',


    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    LANGUAGE_CHANGE: 'LANGUAGE_CHANGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    PROCESS_LOGOUTAFTER: 'PROCESS_LOGOUTAFTER',
    PROCESS_TOTALPAGE: 'PROCESS_TOTALPAGE',
    LOGOUT_HOME: 'LOGOUT_HOME',
    PROCESS_ALLANSWER: 'PROCESS_ALLANSWER',
    HANDLEALLMENU: 'HANDLEALLMENU',
    HANDLEALLSTATESAVE: 'HANDLEALLSTATESAVE',
    HANDLETEST: 'HANDLETEST',
    HANDLEBOOKINGCHILD: 'HANDLEBOOKINGCHILD',
    CHONSENEW: 'CHONSENEW',
    RESET_STORE: "RESET_STORE"



})

export default actionTypes;